media:
  input: public
  output: /
content:
  - name: posts
    label: Posts
    type: collection
    path: src/content/blog
    view:
      fields: [ title, description, draft, date ]
    fields:
      - { name: title, label: Title, type: string, required: true }
      - { name: description, label: Description, type: string }
      - { name: slug, label: Slug, type: string, required: true }
      - { name: draft, label: Draft, type: boolean }
      - { name: ogImage, label: Image, type: string, required: true }
      - { name: body, label: Content, type: rich-text }
  - name: home
    label: Home page
    type: file
    path: src/pages/index.md
    fields:
      - { name: layout, type: string, hidden: true, default: "../layouts/BaseLayout.astro" }
      - { name: pageTitle, label: Page Title, type: string, required: true }
      - { name: heading, label: Heading, type: string, required: true }
      - { name: subHeading, label: Sub-Heading, type: string }
      - { name: blogHeading, label: Blog Heading, type: string, required: true }
